version: '3'
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: 'mysql2://database/waker_development?encoding=utf8mb4&collation=utf8mb4_unicode_ci'
      REDIS_HOST: cache
    depends_on:
      - database
      - cache
  database:
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: waker_development
  cache:
    image: redis
